language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "4.2"
  - "node"

before_install:
  - "npm install coveralls"

script:
  - "npm run test"
  - "npm run cover"

after_success:
  - "cat ./coverage/lcov.info | `npm bin`/coveralls --verbose"
