language: node_js
node_js:
  - "0.11"
  - "0.10"

before_install:
  - "npm install coveralls"

script:
  - "npm run test"
  - "npm run cover"

after_success:
  - "cat ./coverage/lcov.info | `npm bin`/coveralls --verbose"
